server:
  port: 9200

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 动态路由
      routes:
        - id: product_findAll
#          uri: http://localhost:9000
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/findAll
#            - After=ZonedDateTime zdt = new ZonedDateTime();

        - id: product_find
#          uri: http://localhost:9000
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/find

        - id: order_service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**